import { skillsImgs, projectsImgs } from './data_images';
import { FaGithub, FaLinkedin, FaPhoneAlt } from "react-icons/fa";
import { MdMail } from "react-icons/md";

export const skillsData = [
    { img: skillsImgs.tailwind, alt: 'Tailwind', title: 'Tailwind' },
    { img: skillsImgs.react, alt: 'React', title: 'React' },
    { img: skillsImgs.uiUx, alt: 'UI/UX', title: 'UI/UX' },
    { img: skillsImgs.jQuery, alt: 'jQuery', title: 'jQuery' },
    { img: skillsImgs.flutter, alt: 'Flutter', title: 'Flutter' },
    { img: skillsImgs.sql, alt: 'SQL', title: 'SQL' },
    { img: skillsImgs.api, alt: 'API', title: 'API' },
    { img: skillsImgs.godot, alt: 'Godot', title: 'Godot' },
    { img: skillsImgs.css, alt: 'CSS', title: 'CSS' },
    { img: skillsImgs.bootstrap, alt: 'Bootstrap', title: 'Bootstrap' },
    { img: skillsImgs.redux, alt: 'Redux', title: 'Redux' },
    { img: skillsImgs.figma, alt: 'Figma', title: 'Figma' },
    { img: skillsImgs.nodeJs, alt: 'NodeJs', title: 'NodeJs' },
    { img: skillsImgs.mongoDb, alt: 'mongoDB', title: 'mongoDB' },
    { img: skillsImgs.html, alt: 'HTML', title: 'HTML' },
    { img: skillsImgs.js, alt: 'javaScript', title: 'javaScript' },
    { img: skillsImgs.github, alt: 'Github', title: 'Github' },
    { img: skillsImgs.next, alt: 'NextJs', title: 'NextJs' },
    { img: skillsImgs.seo, alt: 'seo', title: 'SEO' },
];

export const projectItems = [
    {
        id: 5,
        imgSrc: projectsImgs.arabhardwareMainApp,
        name: "Arabhardware Application",
        description: "Arabhardware Mobile Application for latest news/events/reviews...",
        using: "Flutter",
        infoLink: "/arabhardware-main-app",
        codeLink: "https://play.google.com/store/apps/details?id=com.arabhardware.mainapp&hl=en-US&pli=1",
        demoLink: "https://play.google.com/store/apps/details?id=com.arabhardware.mainapp&hl=en-US&pli=1",
    },
    {
        id: 6,
        imgSrc: projectsImgs.nvidiaOffice,
        name: "Nvidia Office",
        description: "Nvidia official website for office booking in Cairo",
        using: "Nextjs / TailwindCss",
        infoLink: "/Myaccount",
        codeLink: "https://nvidia-office.vercel.app/en",
        demoLink: "https://nvidia-office.vercel.app/en",
    },
    {
        id: 7,
        imgSrc: projectsImgs.nvidiaNights5,
        name: "Nvidia Nights 5",
        description: "Nvidia Nights using Nextjs, tailwindcss",
        using: "Nextjs / Framer motion / TailwindCss",
        infoLink: "/nvidiaNights5",
        codeLink: "https://www.nvidiasn5.com/en",
        demoLink: "https://www.nvidiasn5.com/en",
    },
    {
        id: 8,
        imgSrc: projectsImgs.myaccount,
        name: "My Account",
        description: "Arabhardware my account website for logging in and searching throughout the websites using Nextjs, tailwindcss, APIs, HeroUI",
        using: "Nextjs / HeroUI / TailwindCss",
        infoLink: "/Myaccount",
        codeLink: "https://myaccount.arabhardware.com/",
        demoLink: "https://myaccount.arabhardware.com/",
    },
    {
        id: 9,
        imgSrc: projectsImgs.ramadanraid25,
        name: "Ramadan Raid 25",
        description: "Arabhardware Ramadan Raid 2025 Event using Nextjs, tailwindcss, APIs, HeroUI",
        using: "Nextjs / HeroUI / TailwindCss / Qr-Reader",
        infoLink: "/ramadanraid25",
        codeLink: "https://ramadanraid25.vercel.app/",
        demoLink: "https://ramadanraid25.vercel.app/",
    },
    {
        id: 10,
        imgSrc: projectsImgs.trendlix,
        name: "Trendlix",
        description: "A website full of cool animations to give the spirit of the agency (from the past to the future)",
        using: "Nextjs / Nodejs / MongoDB / TailwindCss",
        infoLink: "/trendlix",
        codeLink: "https://github.com/ranim-taboush/trendlix",
        demoLink: "https://trendlix-project.vercel.app/",
    },
    {
        id: 11,
        imgSrc: projectsImgs.arabtec,
        name: "Arabtec",
        description: "Full stack with nodejs, nextjs, tailwindcss, gsap, and mongodb",
        using: "Nextjs / Nodejs / MongoDB / TailwindCss",
        infoLink: "/arabtec",
        codeLink: "https://github.com/ranim-taboush/arabtec",
        demoLink: "https://arabtec-five.vercel.app/en",
    },
    {
        id: 12,
        imgSrc: projectsImgs.trendlixProfile,
        name: "Trendlix Profile",
        description: "Instead of plain pdf, this company profile is a swiper",
        using: "Nextjs / Swiperjs",
        infoLink: "/trendlix-profile",
        codeLink: "https://github.com/ranim-taboush/trendlix-profile",
        demoLink: "https://trendlix-profile.vercel.app/",
    },
    {
        id: 13,
        imgSrc: projectsImgs.djm,
        name: "DJM Gold",
        description: "Gold Brand that is divided to Vivaci and SIPA, this website have an admin dashboard and authentication to add products for Vivaci or Sipa, and uses api to get the current gold prices in Egypt",
        using: "Nextjs / Nodejs / MongoDB / TailwindCss",
        infoLink: "/djm",
        codeLink: "https://github.com/ranim-taboush/djm",
        demoLink: "https://djm-eg.com/",
    },
    {
        id: 14,
        imgSrc: projectsImgs.ecmf,
        name: "ECMF",
        description: "Solid Company, this website have an admin panel to add, show, delete products and an admin panel for adding new blogs for better SEO",
        using: "Nextjs / Nodejs / MongoDB / TailwindCss",
        infoLink: "/ecmf",
        codeLink: "https://github.com/ranim-taboush/ecmf",
        demoLink: "https://www.ecmf-eg.com/",
    },
    {
        id: 15,
        imgSrc: projectsImgs.maggdit,
        name: "Maggadit",
        description: "Libyan Food Company that makes different sort of sauces, front end, fully responsive website",
        using: "Nextjs / TailwindCss",
        infoLink: "/maggadit",
        codeLink: "https://github.com/ranim-taboush/maggadit",
        demoLink: "https://www.maggadit.com/",
    },
    {
        id: 16,
        imgSrc: projectsImgs.casadel,
        name: "Casadel Design",
        description: "Furniture website, frontend, fully responsive",
        using: "Nextjs / TailwindCss",
        infoLink: "/casadel",
        codeLink: "https://github.com/ranim-taboush/casadel",
        demoLink: "https://www.cdd-eg.com/",
    },
    {
        id: 17,
        imgSrc: projectsImgs.farawlatech,
        name: "Farawla Tech",
        description: "Made the blogs admin panel, and collaborate on the frontend",
        using: "Nextjs / Nodejs / MongoDB / TailwindCss",
        infoLink: "/farawla-tech",
        codeLink: "https://github.com/ranim-taboush/farawla-tech",
        demoLink: "https://www.farawlatech.com/en",
    },
    {
        id: 18,
        imgSrc: projectsImgs.windows,
        name: "Window",
        description: "A backend using Nodejs and Mongodb, a website similar to Windows24 website, with all its customization",
        using: "Nodejs / MongoDB",
        infoLink: "/windows",
        codeLink: "https://github.com/ranim-taboush/windows",
        demoLink: "https://trendlix-project.vercel.app/",
    },
    {
        id: 19,
        imgSrc: projectsImgs.ahwApp,
        name: "Arabhardware Application",
        description: "I worked on this app as a flutter developer, the backend wasn't handled by me",
        using: "Flutter / MVVM",
        infoLink: "/ahw-app",
        codeLink: "https://github.com/ranim-taboush/arabhardware-application",
        demoLink: "https://play.google.com/store/apps/details?id=com.arabhardware.mainapp",
    },
    {
        id: 1,
        imgSrc: projectsImgs.studentStore,
        name: "Student Store",
        description: "I worked on this app as a QA Engineer as well as a flutter developer, I've helped fix bugs and adding new features to inhance the ux of the site, I also contribute in the onboarding process of the fresh employee",
        using: "Flutter / MVVM / QA",
        infoLink: "/studentStore",
        codeLink: "https://play.google.com/store/apps/details?id=com.nbs.StudentStore",
        demoLink: "https://play.google.com/store/apps/details?id=com.nbs.StudentStore",
    },
    {
        id: 2,
        imgSrc: projectsImgs.ultimateChat,
        name: "Ultimate Chat",
        description: "Online chat where the user can sign in and enter the chat using his google email address, It was made using firebase, firestore, and javascript, with simple design that is compatable with mobiles",
        using: "Javascript / Firebase",
        infoLink: "/ultimateChat",
        codeLink: "https://github.com/Ran-sy/ultimate-chat/",
        demoLink: "https://ran-sy.github.io/ultimate-chat/",
    },
    {
        id: 3,
        imgSrc: projectsImgs.simpleCalculator,
        name: "Simple Calculator",
        description: "Enter the first value on the top, and the second on the bottom, and then press the wanted operation, this will result that the bottom box will have the result of the operation, and it will be shown as will in the result place, and the top box to be empty and ready for the next operation",
        using: "React-JS",
        infoLink: "/simpleCalculator",
        codeLink: "https://github.com/Ran-sy/extremely-simple-calculator",
        demoLink: "https://ran-sy.github.io/extremely-simple-calculator/",
    },
    {
        id: 4,
        imgSrc: projectsImgs.gameCenter,
        name: "Game Center",
        description: "Number of games that you can try to play them now, they are simple games, like: memory, and they were fun to make and test",
        using: "Javascript",
        infoLink: "/gameCenter",
        codeLink: "https://github.com/Ran-sy/game-center",
        demoLink: "https://ran-sy.github.io/game-center/",
    },
    {
        id: 5,
        imgSrc: projectsImgs.miniStore,
        name: "Mini Store",
        description: "Mini store will show you products with pagination, You can add products to the cart, as well as removing them, you can also confirm the shopping process, it was made only html, css, and js ",
        using: "Javascript",
        infoLink: "/miniStore",
        codeLink: "https://github.com/Ran-sy/mini-store",
        demoLink: "https://ran-sy.github.io/mini-store/",
    },
    {
        id: 6,
        imgSrc: projectsImgs.website1,
        name: "First Website",
        description: "It was my first project that i made while attending the web design online course",
        using: "HTML / CSS",
        infoLink: "/website1",
        codeLink: "https://github.com/Ran-sy/website1",
        demoLink: "https://ran-sy.github.io/website1/",
    },
    {
        id: 7,
        imgSrc: projectsImgs.website2,
        name: "Second Website",
        description: "It was my second project that i made while attending the web design online course",
        using: "HTML / CSS / BOOTSTRAP",
        infoLink: "/website2",
        codeLink: "https://github.com/Ran-sy/website2",
        demoLink: "https://ran-sy.github.io/website2/",
    },
    {
        id: 8,
        imgSrc: projectsImgs.website3,
        name: "Third Website",
        description: "It was my third project that i made while attending the web design online course",
        using: "HTML / CSS / BOOTSTRAP",
        infoLink: "/webstie3",
        codeLink: "https://github.com/Ran-sy/website3",
        demoLink: "https://ran-sy.github.io/website3/",
    },
    {
        id: 9,
        imgSrc: projectsImgs.animalRace,
        name: "Animal Race",
        description: "I've made this during a course i took and it was a lot of fun to make it and watch it, i know i could have done other interesting patterns but i wanted something unique and joyfull",
        using: "CSS / Animation",
        infoLink: "/animalRace",
        codeLink: "https://github.com/Ran-sy/animals-race-animation",
        demoLink: "https://ran-sy.github.io/animals-race-animation/",
    },
];

export const social = [
    { title: "linkedIn", icon: FaLinkedin, href: "https://www.linkedin.com/in/ranim-t-a36483182/" },
    { title: "github", icon: FaGithub, href: "https://github.com/ranim-taboush" },
    { title: "email", icon: MdMail, href: "mailto:ranim.taboush@gmail.com" },
];
